### PR TITLE
Feat/gui

### PR DESCRIPTION
**Pull request by isacpaulsson**

### CODE REVIEW

**Comment by isacpaulsson** [comment]
> I'm most likely doing something wrong, but how do I run the gui? I run `make dll` and then `make prun`, but I get nothing? 😕 Perhaps a short description could clear up some things.

I corrected the makefile and the gui can now be run as described

**Review by mosmar99 — CHANGES_REQUESTED** [review]
Great job, looks good to me! 

Just a few things I would like to note.
I tried running the game in Ubuntu but it did not work. Creating the shared library worked. To run the make file in Ubuntu we must use forward slash in the make file instead of backslash. I.e. "python3 "./python/chess.py" instead of "python3 ".\python\chess.py". If foward slash doesn't work in Windows maybe we should have two run-commands in the makefile. One for windows and one for Ubuntu Linux? Say, "prunw" (python-run-windows) for windows and "prunu" (python-run-ubuntu). 

Secondly, the game is tilted horizontally for me? This almost makes it impossible to play a regular game for either player. It would be brilliant if we could do a GUI version of the CLI in the sense of a rotating board. I.e. when its whites turn, he should see the board from his perspective and vice versa. 

With those changes I think that the GUI would be even greater.

**Comment by mosmar99** [comment]
> > I'm most likely doing something wrong, but how do I run the gui? I run `make dll` and then `make prun`, but I get nothing? confused Perhaps a short description could clear up some things.
> 
> I corrected the makefile and the gui can now be run as described

I think that the configurations were fine, for Ubuntu. In the latest commit I've added configurations for Ubuntu as per the description in my previous comment.

**Comment by isacpaulsson** [comment]
I implemented flipping of the board as per your suggestion @mosmar99, this still needs some work like taking time between turns to not make it so jarring. but it works for now 🙂

**Comment by mosmar99** [comment]
> 

Looks good to me!

**Pull request merged**
